# Foundamentos Machine Learning 

## Sessão 1, Part b: Reading Data Lab

In [1]:
# Imports
import sqlite3 as sq3
import pandas.io.sql as pds
import pandas as pd

## Lab Exercise: Lendo arquivos no banco de dados

- Crie uma variável chamada caminho, contendo o caminho para o baseball.db contido em resources/.

- Crie uma conexão, con, que esteja conectada ao banco de dados em caminho.
- Crie uma variável chamada consulta, contendo uma consulta SQL que lê todos os dados da tabela allstarfull.
Crie uma variável chamada observações, usando o pandas.[read_sql](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01)

### Opcional
 
- Crie uma variável chamada tabelas, que lê todos os dados da tabela sqlite_master.

- Suponha que você esteja interessado em criar um novo Hall da Fama do beisebol. Junte e analise as tabelas para avaliar os 3 melhores jogadores de beisebol de todos os tempos.

In [15]:
# Download the database
!wget -P data https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML0232EN-SkillsNetwork/asset/baseball.db

--2024-03-06 12:03:15--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML0232EN-SkillsNetwork/asset/baseball.db
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)...

169.63.118.104
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.63.118.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7626752 (7.3M) [binary/octet-stream]
Saving to: ‘data/baseball.db’

baseball.db         100%[===================>]   7.27M  44.4KB/s    in 3m 5s

2024-03-06 12:06:24 (40.4 KB/s) - ‘data/baseball.db’ saved [7626752/7626752]

In [16]:
path = 'data/baseball.db'
con = sq3.Connection(path)

In [17]:
# Executar uma consulta para obter as tabelas disponíveis
cursor = con.execute("SELECT name FROM sqlite_master WHERE type='table';")

# Extrair os resultados
tables = cursor.fetchall()

# Imprimir as tabelas disponíveis
for table in tables:
    print(table[0])

allstarfull
schools
batting

In [19]:
# Carregar os dados da tabela allstarfull
allstarfull_data = pd.read_sql('SELECT * FROM allstarfull', con)

# Visualizar as primeiras 6 linhas
print(allstarfull_data.head(6))

   index   playerID  yearID  gameNum        gameID teamID lgID   GP  \
0      0  gomezle01    1933        0  ALS193307060    NYA   AL  1.0
1      1  ferreri01    1933        0  ALS193307060    BOS   AL  1.0
2      2  gehrilo01    1933        0  ALS193307060    NYA   AL  1.0
3      3  gehrich01    1933        0  ALS193307060    DET   AL  1.0
4      4  dykesji01    1933        0  ALS193307060    CHA   AL  1.0
5      5  cronijo01    1933        0  ALS193307060    WS1   AL  1.0

   startingPos
0          1.0
1          2.0
2          3.0
3          4.0
4          5.0
5          6.0

In [3]:
### BEGIN SOLUTION

import sqlite3 as sq3
import pandas as pd

# Create a variable, `path`, containing the path to the `baseball.db` contained in `resources/`
path = 'data/baseball.db'

# Create a connection, `con`, that is connected to database at `path`
con = sq3.Connection(path)

# Create a variable, `query`, containing a SQL query which reads in all data from the `` table

query = """
SELECT *
    FROM allstarfull
    ;
"""

allstar_observations = pd.read_sql(query, con)

# print(allstar_observations)

# Create a variable, tables, which reads in all data from the table sqlite_master
all_tables = pd.read_sql('SELECT * FROM allstarfull', con)
print(all_tables)

# Pretend that you were interesting in creating a new baseball hall of fame. Join and analyze the tables to evaluate the top 3 all time best baseball players
best_query = """
SELECT playerID, sum(GP) AS num_games_played, AVG(startingPos) AS avg_starting_position
    FROM allstarfull
    GROUP BY playerID
    ORDER BY num_games_played DESC, avg_starting_position ASC
    LIMIT 3
"""
best = pd.read_sql(best_query, con)
print(best.head())
### END SOLUTION

      index   playerID  yearID  gameNum        gameID teamID lgID   GP  \
0         0  gomezle01    1933        0  ALS193307060    NYA   AL  1.0
1         1  ferreri01    1933        0  ALS193307060    BOS   AL  1.0
2         2  gehrilo01    1933        0  ALS193307060    NYA   AL  1.0
3         3  gehrich01    1933        0  ALS193307060    DET   AL  1.0
4         4  dykesji01    1933        0  ALS193307060    CHA   AL  1.0
...     ...        ...     ...      ...           ...    ...  ...  ...
5143   5143  seageco01    2016        0  ALS201607120    LAN   NL  1.0
5144   5144  strasst01    2016        0  ALS201607120    WAS   NL  0.0
5145   5145  syndeno01    2016        0  ALS201607120    NYN   NL  0.0
5146   5146  teherju01    2016        0  ALS201607120    ATL   NL  1.0
5147   5147  zobribe01    2016        0  ALS201607120    CHN   NL  1.0

      startingPos
0             1.0
1             2.0
2             3.0
3             4.0
4             5.0
...           ...
5143          NaN
5144          NaN
5145          NaN
5146          NaN
5147          4.0

[5148 rows x 9 columns]
    playerID  num_games_played  avg_starting_position
0  musiast01              24.0               6.357143
1   mayswi01              24.0               8.000000
2  aaronha01              24.0               8.470588

---
### Machine Learning Foundation (C) 2020 IBM Corporation